### ISSUE TITLE
Demo page doesn't work in IE9

### ISSUE THREAD

**Issue by trante** [mathiasbynens/jquery-details#7]
I tried this demo page:
http://mathiasbynens.be/demo/html5-details-jquery

But it doesn't work in IE9.
My user agent is:
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; MAAU; MAAU)

**Comment by nicekiwi** [comment]
Sorry, but this plugin does NOT work in IE9. :(

**Comment by nicekiwi** [comment]
Ok, this is weird. When I first goto the page, as you see in the Youtube video the plugin appears not to work. But as Soon as I open the Dev tools it starts working?? If I refresh the page with Dev tools open it works. But if I close Dev tools and Close the tab, then go back with Dev tools closed. Again it will not work.

**Comment by dascritch** [comment]
Seems like a console call .

Envoyé via internet
